export * from './HeroSection'
export * from './OurFeatures'
export * from './RightImageSection'
export * from './LeftImageSection'
export * from './OtherFeatures'
export * from './OurPricing'
export * from './Faqs'
export * from './CustomerReviews'